INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Soumeya','email1@gmail.com','feminin',2001-12-10,'ettente','12345678');
INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Mohamed','email2@gmail.com','masculin',1991-02-23,'ettente','abc123');
INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Ali','email3@gmail.com','masculin',1981-08-18,'ettente','123abc');
INSERT INTO `images`(`chemin`) VALUES ('facebook.png');
INSERT INTO `images`(`chemin`) VALUES ('email.png');
INSERT INTO `images`(`chemin`) VALUES ('numero.png');
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('facebook','my-facebook',1);
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('email','email@gmail.com',2);
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('numero','00 11 22 33 44',3);
INSERT INTO `marques` () VALUES ('','','');
INSERT INTO `admins` (`username`,`pwd`) VALUES ('admin','admin');
