INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Soumeya','email1@gmail.com','feminin',2001-12-10,'ettente','12345678');
INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Mohamed','email2@gmail.com','masculin',1991-02-23,'ettente','abc123');
INSERT INTO `users`(`user_nom`, `user_prenom`, `email`, `sexe`, `date_naissance`, `status`, `mdp`) VALUES ('Mekki','Ali','email3@gmail.com','masculin',1981-08-18,'ettente','123abc');
INSERT INTO `admins` (`username`,`pwd`) VALUES ('admin','admin');
INSERT INTO `images`(`chemin`) VALUES ('facebook.png');
INSERT INTO `images`(`chemin`) VALUES ('email.png');
INSERT INTO `images`(`chemin`) VALUES ('numero.png');
INSERT INTO `images`(`chemin`) VALUES ('ford.png');
INSERT INTO `images`(`chemin`) VALUES ('hyundai.png');
INSERT INTO `images`(`chemin`) VALUES ('skoda.png');
INSERT INTO `images`(`chemin`) VALUES ('suzuki.png');
INSERT INTO `images`(`chemin`) VALUES ('toyota.jpg');
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('facebook','my-facebook',1);
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('email','email@gmail.com',2);
INSERT INTO `contacts` (`contact_nom`,`value`,`image_id`) VALUES ('numero','00 11 22 33 44',3);
INSERT INTO `marques` (`marque_nom`, `pays_origine`, `siege_social`, `annee_creation`, `supp`, `principale`, `guide_id`, `image_id`) VALUES ('Skoda', 'Tchequie', 'Boleslav', '1895', '0', '1', NULL, '11');
INSERT INTO `marques` (`marque_nom`, `pays_origine`, `siege_social`, `annee_creation`, `supp`, `principale`, `guide_id`, `image_id`) VALUES ('Hyundai', 'États-Unis', 'Californie', '1986', '0', '1', NULL, '10');
INSERT INTO `marques` (`marque_nom`, `pays_origine`, `siege_social`, `annee_creation`, `supp`, `principale`, `guide_id`, `image_id`) VALUES ('Ford', 'États-Unis', 'Michigan', '1903', '0', '1', NULL, '9');
INSERT INTO `marques` (`marque_nom`, `pays_origine`, `siege_social`, `annee_creation`, `supp`, `principale`, `guide_id`, `image_id`) VALUES ('Suzuki', 'Japon', 'Hamamatsu', '1909', '0', '1', NULL, '12');
INSERT INTO `marques` (`marque_nom`, `pays_origine`, `siege_social`, `annee_creation`, `supp`, `principale`, `guide_id`, `image_id`) VALUES ('Toyota', 'Japon', 'Aichi', '1926', '0', '1', NULL, '13');  